spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/feng?useSSL=false
    username: root
    password: root
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
  http:
    encoding:
      charset: utf-8
      force-response: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB